/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R404RouteImport } from './routes/404'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppTvRouteImport } from './routes/_app.tv'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServerRouteImport } from './routes/_app.server'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppMoviesIndexRouteImport } from './routes/_app.movies.index'
import { Route as AppListsWatchListRouteImport } from './routes/_app.lists.watch-list'
import { Route as AppListsLikeRouteImport } from './routes/_app.lists.like'
import { Route as AppListsHistoryRouteImport } from './routes/_app.lists.history'
import { Route as AppMoviesMovieIdIndexRouteImport } from './routes/_app.movies.$movieId.index'
import { Route as AppMoviesMovieIdTorrentsRouteImport } from './routes/_app.movies.$movieId.torrents'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTvRoute = AppTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServerRoute = AppServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesIndexRoute = AppMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => AppRoute,
} as any)
const AppListsWatchListRoute = AppListsWatchListRouteImport.update({
  id: '/lists/watch-list',
  path: '/lists/watch-list',
  getParentRoute: () => AppRoute,
} as any)
const AppListsLikeRoute = AppListsLikeRouteImport.update({
  id: '/lists/like',
  path: '/lists/like',
  getParentRoute: () => AppRoute,
} as any)
const AppListsHistoryRoute = AppListsHistoryRouteImport.update({
  id: '/lists/history',
  path: '/lists/history',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesMovieIdIndexRoute = AppMoviesMovieIdIndexRouteImport.update({
  id: '/movies/$movieId/',
  path: '/movies/$movieId/',
  getParentRoute: () => AppRoute,
} as any)
const AppMoviesMovieIdTorrentsRoute =
  AppMoviesMovieIdTorrentsRouteImport.update({
    id: '/movies/$movieId/torrents',
    path: '/movies/$movieId/torrents',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/404': typeof R404Route
  '/search': typeof AppSearchRoute
  '/server': typeof AppServerRoute
  '/settings': typeof AppSettingsRoute
  '/tv': typeof AppTvRoute
  '/users': typeof AppUsersRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/lists/history': typeof AppListsHistoryRoute
  '/lists/like': typeof AppListsLikeRoute
  '/lists/watch-list': typeof AppListsWatchListRoute
  '/movies': typeof AppMoviesIndexRoute
  '/movies/$movieId/torrents': typeof AppMoviesMovieIdTorrentsRoute
  '/movies/$movieId': typeof AppMoviesMovieIdIndexRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/search': typeof AppSearchRoute
  '/server': typeof AppServerRoute
  '/settings': typeof AppSettingsRoute
  '/tv': typeof AppTvRoute
  '/users': typeof AppUsersRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/lists/history': typeof AppListsHistoryRoute
  '/lists/like': typeof AppListsLikeRoute
  '/lists/watch-list': typeof AppListsWatchListRoute
  '/movies': typeof AppMoviesIndexRoute
  '/movies/$movieId/torrents': typeof AppMoviesMovieIdTorrentsRoute
  '/movies/$movieId': typeof AppMoviesMovieIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/404': typeof R404Route
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/search': typeof AppSearchRoute
  '/_app/server': typeof AppServerRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tv': typeof AppTvRoute
  '/_app/users': typeof AppUsersRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/lists/history': typeof AppListsHistoryRoute
  '/_app/lists/like': typeof AppListsLikeRoute
  '/_app/lists/watch-list': typeof AppListsWatchListRoute
  '/_app/movies/': typeof AppMoviesIndexRoute
  '/_app/movies/$movieId/torrents': typeof AppMoviesMovieIdTorrentsRoute
  '/_app/movies/$movieId/': typeof AppMoviesMovieIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/search'
    | '/server'
    | '/settings'
    | '/tv'
    | '/users'
    | '/login'
    | '/signup'
    | '/'
    | '/lists/history'
    | '/lists/like'
    | '/lists/watch-list'
    | '/movies'
    | '/movies/$movieId/torrents'
    | '/movies/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/search'
    | '/server'
    | '/settings'
    | '/tv'
    | '/users'
    | '/login'
    | '/signup'
    | '/'
    | '/lists/history'
    | '/lists/like'
    | '/lists/watch-list'
    | '/movies'
    | '/movies/$movieId/torrents'
    | '/movies/$movieId'
  id:
    | '__root__'
    | '/404'
    | '/_app'
    | '/_auth'
    | '/_app/search'
    | '/_app/server'
    | '/_app/settings'
    | '/_app/tv'
    | '/_app/users'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/lists/history'
    | '/_app/lists/like'
    | '/_app/lists/watch-list'
    | '/_app/movies/'
    | '/_app/movies/$movieId/torrents'
    | '/_app/movies/$movieId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tv': {
      id: '/_app/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AppTvRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/server': {
      id: '/_app/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof AppServerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/': {
      id: '/_app/movies/'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AppMoviesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/watch-list': {
      id: '/_app/lists/watch-list'
      path: '/lists/watch-list'
      fullPath: '/lists/watch-list'
      preLoaderRoute: typeof AppListsWatchListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/like': {
      id: '/_app/lists/like'
      path: '/lists/like'
      fullPath: '/lists/like'
      preLoaderRoute: typeof AppListsLikeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/history': {
      id: '/_app/lists/history'
      path: '/lists/history'
      fullPath: '/lists/history'
      preLoaderRoute: typeof AppListsHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/$movieId/': {
      id: '/_app/movies/$movieId/'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof AppMoviesMovieIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/movies/$movieId/torrents': {
      id: '/_app/movies/$movieId/torrents'
      path: '/movies/$movieId/torrents'
      fullPath: '/movies/$movieId/torrents'
      preLoaderRoute: typeof AppMoviesMovieIdTorrentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSearchRoute: typeof AppSearchRoute
  AppServerRoute: typeof AppServerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTvRoute: typeof AppTvRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppListsHistoryRoute: typeof AppListsHistoryRoute
  AppListsLikeRoute: typeof AppListsLikeRoute
  AppListsWatchListRoute: typeof AppListsWatchListRoute
  AppMoviesIndexRoute: typeof AppMoviesIndexRoute
  AppMoviesMovieIdTorrentsRoute: typeof AppMoviesMovieIdTorrentsRoute
  AppMoviesMovieIdIndexRoute: typeof AppMoviesMovieIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSearchRoute: AppSearchRoute,
  AppServerRoute: AppServerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTvRoute: AppTvRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppListsHistoryRoute: AppListsHistoryRoute,
  AppListsLikeRoute: AppListsLikeRoute,
  AppListsWatchListRoute: AppListsWatchListRoute,
  AppMoviesIndexRoute: AppMoviesIndexRoute,
  AppMoviesMovieIdTorrentsRoute: AppMoviesMovieIdTorrentsRoute,
  AppMoviesMovieIdIndexRoute: AppMoviesMovieIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
